# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_lost',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Lost'),
            preserve_default=False,
        ),
    ]
