# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_auto_20171130_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_lost',
            field=models.DateTimeField(),
        ),
    ]
