# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0009_auto_20171201_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_lost',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 2, 1, 15, 30, 582278, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
