# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0011_auto_20171204_1710'),
        ('lostandfound', '0014_auto_20171202_0328'),
    ]

    operations = [
    ]
